### PR TITLE
Mirror README changes from original site

### PR DESCRIPTION
**Pull request by edani**
@fommil pushed a change to the original ensime site's README , here is the same thing for the ensime organization (I added a wiki link as well)

### CODE REVIEW

**Comment by edani** [comment]
This pull request may be wrong or premature, can you hold off on it? Sorry if I'm causing any confusion!

**Comment by rajish** [comment]
I don't like the idea of sending PRs here and reporting issues there so I wouldn't merge it anyway.
Everything should be kept in one place, and I think we should wait with README updates until everything clears up.

**Comment by fommil** [comment]
yes, looks like the cleanest thing is for aemon to reset his master to the master from here, and then give ownership to the `ensime` org. That will fix a lot of things.

**Comment by fommil** [comment]
Close?

**Pull request closed without merging**
